### PR TITLE
Don't invoke make directly; use CMAKE_BUILD_TOOL

### PR DESCRIPTION
**Pull request by ke6jjj**
This project depends on GNUMake, which may not be called `make` on
all systems. Use the more portable `CMAKE_BUILD_TOOL` variable instead.

### CODE REVIEW

**Comment by JayKickliter** [comment]
let's hold off on merging this because erlang-pbc builds are failing on at least macOS after merging a similar PR. It shouldn't break anything, but I want to find the root cause

**Comment by ke6jjj** [comment]
@JayKickliter which branch is failing? I can test on MacOS and probably get to that root cause.

**Comment by evanmcc** [comment]
master and patch-1 are failing on big sur

**Comment by ke6jjj** [comment]
I see it:
```
checking whether we are cross compiling... configure: error: in `/Users/jeremy/src/git/erlang-erasure-check/_build/c_src/gf-complete/src/gf-complete':
configure: error: cannot run C compiled programs.
If you meant to cross compile, use `--host'.
See `config.log' for more details
make[3]: *** [gf-complete/src/gf-complete-stamp/gf-complete-configure] Error 1
make[2]: *** [CMakeFiles/gf-complete.dir/all] Error 2
make[1]: *** [all] Error 2
```

**Comment by ke6jjj** [comment]
Haven't gotten to the bottom of it yet, but I see the issue:

```
configure:3485: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -o conftest -O3 -DNDEBUG   conftest.c  >&5
conftest.c:11:10: fatal error: 'stdio.h' file not found
#include <stdio.h>
         ^~~~~~~~~
1 error generated.
```

**Comment by JayKickliter** [comment]
That's exactly the error that prompted this PR: https://github.com/helium/erlang-pbc/pull/8

**Comment by ke6jjj** [comment]
What I'm noticing is that invoking `cc` as `/usr/bin/cc` produces different behavior than invoking it directly as `/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc`, even though, nominally, `/usr/bin/cc` is just a link for the latter. When compiling with `/usr/bin/cc` things work just fine.

It appears that this version of `clang` is checking `argv[0]` to determine how it should behave.

**Comment by ke6jjj** [comment]
I'm currently reading this Cmake article, which may be our solution:

https://discourse.cmake.org/t/help-with-cc-clang-environment-and-cmake/2221

**Comment by ke6jjj** [comment]
This works:

```
make SDKROOT=`xcrun --show-sdk-path`
```

Now to just find a portable/easy way to ensure it runs.

**Comment by JayKickliter** [comment]
this looks like a potential solution:

```diff
index e3b1f2b..41249e4 100644
--- a/c_src/CMakeLists.txt
+++ b/c_src/CMakeLists.txt
@@ -12,6 +12,11 @@ include(ASan)
 IF (APPLE)
   set(CMAKE_MODULE_LINKER_FLAGS "-flat_namespace -undefined suppress")
   set(CMAKE_MACOSX_RPATH 1)
+  execute_process(COMMAND
+    xcrun --show-sdk-path
+    OUTPUT_VARIABLE APPLE_SDK_ROOT
+    )
+  set(sludgeOS_SDKENV "SDKROOT=${APPLE_SDK_ROOT}")
 ENDIF()

 #
diff --git a/c_src/cmake/FindGFComplete.cmake b/c_src/cmake/FindGFComplete.cmake
index 18fa5ba..6cdd09b 100644
--- a/c_src/cmake/FindGFComplete.cmake
+++ b/c_src/cmake/FindGFComplete.cmake
@@ -19,7 +19,8 @@ ExternalProject_Add(gf-complete
                     $ENV{CONFIGURE_ARGS}
                     CC=${CMAKE_C_COMPILER}
                     CFLAGS=${CMAKE_C_FLAGS_${BUILD_TYPE_UC}}
-  BUILD_COMMAND     make -j
+                    ${sludgeOS_SDKENV}
+  BUILD_COMMAND     make -j ${sludgeOS_SDKENV}
   BUILD_BYPRODUCTS  ${CMAKE_CURRENT_BINARY_DIR}/lib/libgf_complete.a
   INSTALL_COMMAND   make install
   )
diff --git a/c_src/cmake/FindJerasure.cmake b/c_src/cmake/FindJerasure.cmake
index 3b7e800..87db016 100644
--- a/c_src/cmake/FindJerasure.cmake
+++ b/c_src/cmake/FindJerasure.cmake
@@ -23,7 +23,8 @@ ExternalProject_Add(jerasure
                     CC=${CMAKE_C_COMPILER}
                     "CFLAGS=-I${CMAKE_CURRENT_BINARY_DIR}/include ${CMAKE_C_FLAGS_${BUILD_TYPE_UC}}"
                     LDFLAGS=-L${CMAKE_CURRENT_BINARY_DIR}/lib
-  BUILD_COMMAND     make -j
+                    ${sludgeOS_SDKENV}
+  BUILD_COMMAND     make -j ${sludgeOS_SDKENV}
   BUILD_BYPRODUCTS  ${CMAKE_CURRENT_BINARY_DIR}/lib/libJerasure.a
   INSTALL_COMMAND   make install
   )
```

the same needs to be done for the jerasure dep and it we'd need to make sure it's portable (unless there's a better, less-ugly fix you can think of)

**Comment by ke6jjj** [comment]
It's definitely ugly, but I can't think of anything better for now. I tried this and it Works On My Box.

**Comment by JayKickliter** [comment]
do you want to incorporate it into your PR (see updated suggested diff above) so you don't have to rebase? either way is fine

**Comment by ke6jjj** [comment]
Yes, I'm testing right now. Will update this branch with OSX fixes.

**Comment by JayKickliter** [comment]
thanks! And sorry for mixing concerns and stepping on your PR

**Comment by JayKickliter** [comment]
once updated I make check that it still works on older macOS (which I usually run) and linux

I still don't know _why_ passing SDKROOT to autools+make fixes the problem.

**Comment by ke6jjj** [comment]
Happy to mix concerns here. I am an OS X user as well, so this is a two-bugs with one patch win-win for me.

**Comment by ke6jjj** [comment]
Builds under FreeBSD 12.1-amd64 as well, now, too.

**Comment by JayKickliter** [comment]
I've confirmed this works on macOS 10.14 Mojave. CI will test linux

**Comment by JayKickliter** [comment]
we'll need to add this same fix to `erlang-pbc`

**Review by JayKickliter — APPROVED** [review]
Thanks. I'll merge when you think you're done tweaking.

**Comment by ke6jjj** [comment]
I think I'm done! I also updated my `patch-1` branch of `erlang-pbc` just now.

**Comment by JayKickliter** [comment]
>  branch of erlang-pbc just now
that PR merged. mind doing a rebase and reopening a new PR with your branch?
